-- FocusCoin 단어 시드 Part 3/5 — 명사 이어서 (200개)
insert into focuscoin_words (en, kr, pos, ex, ex_kr) values
('difference','차이','n.','Small habits make a difference.','작은 습관이 차이를 만든다.'),
('difficulty','어려움','n.','He overcame every difficulty.','그는 모든 어려움을 극복했다.'),
('direction','방향','n.','We walked in the wrong direction.','우리는 잘못된 방향으로 걸었다.'),
('disaster','재난','n.','The flood was a disaster.','그 홍수는 재난이었다.'),
('discount','할인','n.','Members get a discount.','회원은 할인을 받는다.'),
('discovery','발견','n.','It was an amazing discovery.','그것은 놀라운 발견이었다.'),
('discussion','토론','n.','The discussion lasted an hour.','토론은 한 시간 동안 이어졌다.'),
('disease','질병','n.','Vaccines prevent disease.','백신은 질병을 예방한다.'),
('distance','거리','n.','The distance is two kilometers.','거리는 2킬로미터다.'),
('document','문서','n.','Save the document first.','먼저 문서를 저장하세요.'),
('duty','의무','n.','It is my duty to help.','돕는 것이 내 의무다.'),
('economy','경제','n.','The economy is improving.','경제가 나아지고 있다.'),
('edge','가장자리','n.','Do not stand near the edge.','가장자리 근처에 서지 마세요.'),
('education','교육','n.','Education opens doors.','교육은 기회의 문을 연다.'),
('effect','효과','n.','The medicine had a quick effect.','그 약은 효과가 빨랐다.'),
('effort','노력','n.','Success requires effort.','성공에는 노력이 필요하다.'),
('election','선거','n.','The election is next month.','선거는 다음 달이다.'),
('emergency','비상','n.','Call 119 in an emergency.','비상시 119에 전화하세요.'),
('emotion','감정','n.','Music expresses emotion.','음악은 감정을 표현한다.'),
('employee','직원','n.','The company hired ten employees.','회사는 직원 열 명을 고용했다.'),
('energy','에너지','n.','Save energy at home.','집에서 에너지를 절약하세요.'),
('engine','엔진','n.','The engine started smoothly.','엔진이 부드럽게 시동 걸렸다.'),
('engineer','기술자','n.','My uncle is an engineer.','우리 삼촌은 엔지니어다.'),
('entrance','입구','n.','Meet me at the entrance.','입구에서 만나자.'),
('environment','환경','n.','Protect the environment.','환경을 보호하라.'),
('equipment','장비','n.','The gym has new equipment.','체육관에 새 장비가 있다.'),
('error','오류','n.','I found an error in the code.','코드에서 오류를 발견했다.'),
('evidence','증거','n.','There is no evidence yet.','아직 증거가 없다.'),
('exam','시험','n.','The final exam is next week.','기말시험은 다음 주다.'),
('example','예시','n.','Give me an example.','예를 들어 주세요.'),
('exercise','운동','n.','Daily exercise keeps you healthy.','매일 운동하면 건강을 유지한다.'),
('exhibition','전시회','n.','The art exhibition opens today.','미술 전시회가 오늘 열린다.'),
('expense','지출','n.','Track your monthly expenses.','월 지출을 기록하세요.'),
('expert','전문가','n.','Ask an expert for help.','전문가에게 도움을 요청하세요.'),
('explanation','설명','n.','The explanation was clear.','설명이 명확했다.'),
('expression','표현','n.','Her expression showed joy.','그녀의 표정에 기쁨이 드러났다.'),
('factory','공장','n.','The factory runs day and night.','그 공장은 밤낮으로 돌아간다.'),
('failure','실패','n.','Failure teaches valuable lessons.','실패는 귀중한 교훈을 준다.'),
('familiarity','친숙함','n.','Familiarity brings comfort.','친숙함은 편안함을 준다.'),
('fashion','패션','n.','Fashion changes every season.','패션은 계절마다 바뀐다.'),
('feature','특징','n.','The phone has a new feature.','그 휴대폰에는 새 기능이 있다.'),
('fee','수수료','n.','The entrance fee is 5,000 won.','입장료는 5천 원이다.'),
('feedback','피드백','n.','Customer feedback is valuable.','고객 피드백은 소중하다.'),
('fever','열','n.','The child has a high fever.','아이가 고열이 난다.'),
('field','분야','n.','She works in the medical field.','그녀는 의료 분야에서 일한다.'),
('figure','수치','n.','The sales figures look good.','매출 수치가 좋아 보인다.'),
('flavor','맛','n.','I like the vanilla flavor.','나는 바닐라 맛을 좋아한다.'),
('flight','비행','n.','The flight takes two hours.','비행은 두 시간 걸린다.'),
('flood','홍수','n.','The flood damaged many homes.','홍수가 많은 집을 파손했다.'),
('floor','바닥','n.','The floor is wet, be careful.','바닥이 젖었으니 조심하세요.'),
('forest','숲','n.','The forest is full of life.','숲은 생명으로 가득하다.'),
('fortune','행운','n.','She had the fortune to win.','그녀는 운 좋게 이겼다.'),
('foundation','기초','n.','Trust is the foundation of friendship.','신뢰는 우정의 기초다.'),
('freedom','자유','n.','Freedom comes with responsibility.','자유에는 책임이 따른다.'),
('friendship','우정','n.','Their friendship lasted decades.','그들의 우정은 수십 년 지속됐다.'),
('fuel','연료','n.','The car needs fuel.','차에 연료가 필요하다.'),
('function','기능','n.','Each button has a function.','각 버튼에는 기능이 있다.'),
('furniture','가구','n.','They bought new furniture.','그들은 새 가구를 샀다.'),
('future','미래','n.','Plan for the future.','미래를 계획하라.'),
('garage','차고','n.','Park the car in the garage.','차를 차고에 주차하세요.'),
('garbage','쓰레기','n.','Take out the garbage tonight.','오늘 밤 쓰레기를 내다 버리세요.'),
('generation','세대','n.','Each generation has its style.','각 세대는 고유한 스타일이 있다.'),
('goal','목표','n.','Set a clear goal first.','먼저 명확한 목표를 세우세요.'),
('government','정부','n.','The government announced new rules.','정부가 새 규정을 발표했다.'),
('grade','성적','n.','She got a good grade.','그녀는 좋은 성적을 받았다.'),
('ground','땅','n.','The ground is frozen.','땅이 얼어 있다.'),
('growth','성장','n.','Reading supports mental growth.','독서는 정신적 성장을 돕는다.'),
('guest','손님','n.','We welcomed the guests.','우리는 손님들을 맞이했다.'),
('habit','습관','n.','Good habits change your life.','좋은 습관이 인생을 바꾼다.'),
('harbor','항구','n.','Ships rest in the harbor.','배들이 항구에 정박해 있다.'),
('harmony','조화','n.','They live in harmony.','그들은 조화롭게 산다.'),
('health','건강','n.','Health is the greatest wealth.','건강이 최고의 재산이다.'),
('heart','심장','n.','Exercise strengthens the heart.','운동은 심장을 튼튼하게 한다.'),
('height','높이','n.','What is the height of the tower?','그 탑의 높이는 얼마인가요?'),
('history','역사','n.','History repeats itself.','역사는 반복된다.'),
('hobby','취미','n.','Painting is my hobby.','그림 그리기는 내 취미다.'),
('holiday','휴일','n.','We traveled during the holiday.','우리는 휴일 동안 여행했다.'),
('honesty','정직','n.','Honesty is the best policy.','정직이 최선의 방책이다.'),
('honor','명예','n.','It is an honor to meet you.','만나 뵙게 되어 영광입니다.'),
('hospital','병원','n.','The hospital is open 24 hours.','그 병원은 24시간 운영한다.'),
('host','주최자','n.','The host welcomed everyone.','주최자가 모두를 환영했다.'),
('humor','유머','n.','He has a great sense of humor.','그는 유머 감각이 뛰어나다.'),
('idea','아이디어','n.','That is a brilliant idea.','그것은 훌륭한 아이디어다.'),
('illness','질병','n.','She recovered from her illness.','그녀는 병에서 회복했다.'),
('image','이미지','n.','The image is very clear.','그 이미지는 매우 선명하다.'),
('imagination','상상력','n.','Books spark imagination.','책은 상상력을 자극한다.'),
('importance','중요성','n.','He stressed the importance of sleep.','그는 수면의 중요성을 강조했다.'),
('impression','인상','n.','First impressions matter.','첫인상이 중요하다.'),
('improvement','개선','n.','I see great improvement.','큰 개선이 보인다.'),
('income','수입','n.','His income increased this year.','올해 그의 수입이 늘었다.'),
('industry','산업','n.','The game industry is growing.','게임 산업이 성장하고 있다.'),
('information','정보','n.','Find more information online.','더 많은 정보는 온라인에서 찾아보세요.'),
('ingredient','재료','n.','Mix all the ingredients.','모든 재료를 섞으세요.'),
('injury','부상','n.','He recovered from the injury.','그는 부상에서 회복했다.'),
('insect','곤충','n.','Many insects live in the garden.','정원에는 많은 곤충이 산다.'),
('instance','사례','n.','For instance, try walking daily.','예를 들어, 매일 걷기를 시도해 보세요.'),
('instruction','지시','n.','Read the instructions first.','먼저 설명서를 읽으세요.'),
('instrument','악기','n.','The violin is a beautiful instrument.','바이올린은 아름다운 악기다.'),
('insurance','보험','n.','Travel insurance is useful.','여행자 보험은 유용하다.'),
('interest','관심','n.','She shows interest in art.','그녀는 미술에 관심을 보인다.'),
('interview','면접','n.','The interview went well.','면접이 잘 진행됐다.'),
('invention','발명','n.','The wheel was a great invention.','바퀴는 위대한 발명이었다.'),
('invitation','초대','n.','I received a wedding invitation.','결혼식 초대장을 받았다.'),
('island','섬','n.','The island has white beaches.','그 섬에는 하얀 해변이 있다.'),
('item','물품','n.','Check each item on the list.','목록의 각 항목을 확인하세요.'),
('journey','여정','n.','The journey took three days.','그 여정은 사흘 걸렸다.'),
('judgment','판단','n.','Trust your own judgment.','자신의 판단을 믿어라.'),
('justice','정의','n.','Justice must be fair.','정의는 공정해야 한다.'),
('knowledge','지식','n.','Knowledge is power.','아는 것이 힘이다.'),
('labor','노동','n.','The work requires hard labor.','그 일은 힘든 노동을 요구한다.'),
('laboratory','실험실','n.','Scientists work in the laboratory.','과학자들은 실험실에서 일한다.'),
('language','언어','n.','She speaks three languages.','그녀는 3개 국어를 한다.'),
('laughter','웃음','n.','Laughter is the best medicine.','웃음이 최고의 명약이다.'),
('law','법','n.','Everyone must follow the law.','모든 사람은 법을 따라야 한다.'),
('leader','지도자','n.','A good leader listens well.','좋은 지도자는 잘 듣는다.'),
('lecture','강의','n.','The lecture was very helpful.','그 강의는 매우 유익했다.'),
('leisure','여가','n.','Enjoy your leisure time.','여가 시간을 즐기세요.'),
('length','길이','n.','Measure the length of the table.','테이블 길이를 재 보세요.'),
('lesson','수업','n.','Every failure is a lesson.','모든 실패는 교훈이다.'),
('level','수준','n.','Choose the right level.','알맞은 수준을 선택하세요.'),
('liberty','자유','n.','Liberty is a basic right.','자유는 기본 권리다.'),
('library','도서관','n.','The library opens at nine.','도서관은 9시에 문을 연다.'),
('limit','한계','n.','Push beyond your limits.','한계를 뛰어넘어라.'),
('literature','문학','n.','She studies Korean literature.','그녀는 한국 문학을 공부한다.'),
('location','위치','n.','The location is easy to find.','그 위치는 찾기 쉽다.'),
('luck','행운','n.','Good luck on your test.','시험 잘 봐, 행운을 빌어.'),
('machine','기계','n.','The machine works automatically.','그 기계는 자동으로 작동한다.'),
('magazine','잡지','n.','She reads fashion magazines.','그녀는 패션 잡지를 읽는다.'),
('manner','태도','n.','He spoke in a kind manner.','그는 친절한 태도로 말했다.'),
('market','시장','n.','The market is busy on weekends.','시장은 주말에 붐빈다.'),
('marriage','결혼','n.','Their marriage lasted fifty years.','그들의 결혼 생활은 50년 지속됐다.'),
('material','재료','n.','Gather the materials first.','먼저 재료를 모으세요.'),
('mathematics','수학','n.','Mathematics trains logical thinking.','수학은 논리적 사고를 훈련시킨다.'),
('meaning','의미','n.','What is the meaning of this word?','이 단어의 의미는 무엇인가요?'),
('medicine','약','n.','Take the medicine after meals.','식후에 약을 복용하세요.'),
('memory','기억','n.','That trip is a precious memory.','그 여행은 소중한 기억이다.'),
('message','메시지','n.','I left you a message.','너에게 메시지를 남겼어.'),
('metal','금속','n.','The frame is made of metal.','그 틀은 금속으로 만들어졌다.'),
('method','방법','n.','Try a different method.','다른 방법을 시도해 보세요.'),
('mind','마음','n.','A calm mind works better.','차분한 마음이 더 잘 작동한다.'),
('mistake','실수','n.','Learn from your mistakes.','실수에서 배워라.'),
('moment','순간','n.','Enjoy every moment.','모든 순간을 즐겨라.'),
('mood','기분','n.','Sunshine improves my mood.','햇살이 내 기분을 좋게 한다.'),
('mountain','산','n.','The mountain is covered in snow.','그 산은 눈으로 덮여 있다.'),
('movement','움직임','n.','The dancer made graceful movements.','무용수가 우아한 동작을 했다.'),
('muscle','근육','n.','Stretching relaxes your muscles.','스트레칭은 근육을 이완시킨다.'),
('mystery','미스터리','n.','The case remains a mystery.','그 사건은 여전히 미스터리다.'),
('nation','국가','n.','The whole nation celebrated.','온 나라가 축하했다.'),
('nature','자연','n.','Spend time in nature.','자연에서 시간을 보내세요.'),
('necessity','필수품','n.','Water is a basic necessity.','물은 기본 필수품이다.'),
('neighbor','이웃','n.','My neighbor is very friendly.','우리 이웃은 매우 친절하다.'),
('noise','소음','n.','The noise kept me awake.','소음 때문에 잠을 못 잤다.'),
('notice','공지','n.','Read the notice on the board.','게시판의 공지를 읽으세요.'),
('object','물체','n.','A strange object appeared.','이상한 물체가 나타났다.'),
('occasion','경우','n.','Save the dress for a special occasion.','특별한 날을 위해 그 드레스를 아껴 두세요.'),
('ocean','바다','n.','The ocean is deep and wide.','바다는 깊고 넓다.'),
('opinion','의견','n.','Everyone has a different opinion.','모두가 다른 의견을 가진다.'),
('opportunity','기회','n.','Grab every opportunity.','모든 기회를 잡아라.'),
('option','선택지','n.','You have several options.','당신에게는 여러 선택지가 있다.'),
('origin','기원','n.','The origin of the word is Latin.','그 단어의 기원은 라틴어다.'),
('outcome','결과','n.','The outcome surprised everyone.','그 결과는 모두를 놀라게 했다.'),
('owner','주인','n.','The owner greeted the guests.','주인이 손님들을 맞이했다.'),
('package','소포','n.','The package arrived today.','소포가 오늘 도착했다.'),
('pain','고통','n.','No pain, no gain.','고통 없이는 얻는 것도 없다.'),
('palace','궁전','n.','We visited the old palace.','우리는 오래된 궁전을 방문했다.'),
('passenger','승객','n.','All passengers must wear seatbelts.','모든 승객은 안전벨트를 매야 한다.'),
('passion','열정','n.','Follow your passion.','너의 열정을 따라가라.'),
('password','비밀번호','n.','Change your password regularly.','비밀번호를 정기적으로 바꾸세요.'),
('patient','환자','n.','The doctor visited the patient.','의사가 환자를 방문했다.'),
('pattern','패턴','n.','I see a pattern in the data.','데이터에서 패턴이 보인다.'),
('peace','평화','n.','We all wish for peace.','우리 모두 평화를 바란다.'),
('performance','공연','n.','The performance was amazing.','공연은 놀라웠다.'),
('period','기간','n.','The trial period is 30 days.','체험 기간은 30일이다.'),
('permission','허가','n.','Ask for permission first.','먼저 허락을 구하세요.'),
('personality','성격','n.','She has a bright personality.','그녀는 밝은 성격을 가졌다.'),
('phenomenon','현상','n.','It is a rare natural phenomenon.','그것은 드문 자연 현상이다.'),
('philosophy','철학','n.','His philosophy is simple living.','그의 철학은 소박한 삶이다.'),
('photograph','사진','n.','She took a beautiful photograph.','그녀는 아름다운 사진을 찍었다.'),
('phrase','구절','n.','Repeat the phrase aloud.','그 구절을 소리 내어 반복하세요.'),
('pleasure','기쁨','n.','It was a pleasure to meet you.','만나서 반가웠습니다.'),
('poem','시','n.','She wrote a poem about spring.','그녀는 봄에 관한 시를 썼다.'),
('policy','정책','n.','The new policy starts Monday.','새 정책은 월요일부터 시작된다.'),
('population','인구','n.','The population is growing.','인구가 증가하고 있다.'),
('position','위치','n.','Hold the position for ten seconds.','그 자세를 10초간 유지하세요.'),
('possibility','가능성','n.','There is a possibility of rain.','비가 올 가능성이 있다.'),
('poverty','가난','n.','They fought against poverty.','그들은 가난과 싸웠다.'),
('practice','연습','n.','Daily practice brings progress.','매일의 연습이 발전을 가져온다.'),
('pressure','압박','n.','He works well under pressure.','그는 압박 속에서도 일을 잘한다.'),
('price','가격','n.','The price includes shipping.','가격에 배송비가 포함된다.'),
('pride','자부심','n.','She takes pride in her work.','그녀는 자신의 일에 자부심을 가진다.'),
('principle','원칙','n.','Stick to your principles.','원칙을 지켜라.'),
('priority','우선순위','n.','Health is my top priority.','건강이 나의 최우선이다.'),
('prize','상','n.','She won first prize.','그녀는 1등 상을 받았다.'),
('process','과정','n.','Learning is a slow process.','배움은 느린 과정이다.'),
('product','제품','n.','The new product sells well.','신제품이 잘 팔린다.'),
('profession','직업','n.','Teaching is a noble profession.','가르치는 일은 고귀한 직업이다.'),
('professor','교수','n.','The professor explained clearly.','교수님이 명확하게 설명했다.'),
('profit','이익','n.','The store made a profit.','그 가게는 이익을 냈다.'),
('project','프로젝트','n.','The project ends next week.','프로젝트는 다음 주에 끝난다.'),
('promise','약속','n.','Keep your promise.','약속을 지켜라.'),
('proof','증거','n.','Show me the proof.','증거를 보여 주세요.'),
('property','재산','n.','The property belongs to the city.','그 부동산은 시 소유다.'),
('proposal','제안','n.','The proposal was accepted.','그 제안은 수락되었다.'),
('purpose','목적','n.','What is the purpose of this trip?','이 여행의 목적은 무엇인가요?'),
('quality','품질','n.','Quality matters more than quantity.','양보다 질이 중요하다.'),
('quantity','수량','n.','Order a large quantity.','대량으로 주문하세요.')
on conflict (en) do nothing;
