-- FocusCoin 단어 시드 Part 5/5 — 형용사 이어서 + 부사 (185개)
insert into focuscoin_words (en, kr, pos, ex, ex_kr) values
('handsome','잘생긴','adj.','The actor is very handsome.','그 배우는 매우 잘생겼다.'),
('handy','편리한','adj.','This tool is really handy.','이 도구는 정말 편리하다.'),
('happy','행복한','adj.','She looks happy today.','그녀는 오늘 행복해 보인다.'),
('hard','어려운','adj.','The question was hard.','그 질문은 어려웠다.'),
('harmful','해로운','adj.','Smoking is harmful to health.','흡연은 건강에 해롭다.'),
('healthy','건강한','adj.','Eat healthy food daily.','매일 건강한 음식을 먹어라.'),
('heavy','무거운','adj.','The suitcase is too heavy.','그 여행 가방은 너무 무겁다.'),
('helpful','도움이 되는','adj.','Your advice was helpful.','당신의 조언이 도움이 되었다.'),
('hidden','숨겨진','adj.','The cafe is a hidden gem.','그 카페는 숨은 명소다.'),
('high','높은','adj.','The mountain is very high.','그 산은 매우 높다.'),
('hollow','속이 빈','adj.','The tree trunk is hollow.','그 나무 줄기는 속이 비어 있다.'),
('honest','정직한','adj.','Be honest with yourself.','자신에게 정직하라.'),
('huge','거대한','adj.','They live in a huge house.','그들은 거대한 집에 산다.'),
('humble','겸손한','adj.','Stay humble after success.','성공 후에도 겸손하라.'),
('hungry','배고픈','adj.','I am hungry after the workout.','운동 후에 배가 고프다.'),
('ideal','이상적인','adj.','The weather is ideal for hiking.','등산하기에 이상적인 날씨다.'),
('immediate','즉각적인','adj.','We need an immediate answer.','우리는 즉각적인 답이 필요하다.'),
('important','중요한','adj.','Sleep is important for focus.','수면은 집중에 중요하다.'),
('impossible','불가능한','adj.','Nothing is impossible.','불가능한 것은 없다.'),
('impressive','인상적인','adj.','Her presentation was impressive.','그녀의 발표는 인상적이었다.'),
('independent','독립적인','adj.','She is an independent thinker.','그녀는 독립적인 사색가다.'),
('individual','개인의','adj.','Respect individual choices.','개인의 선택을 존중하라.'),
('inner','내면의','adj.','Find your inner peace.','내면의 평화를 찾아라.'),
('innocent','무고한','adj.','The court found him innocent.','법원은 그가 무죄라고 판결했다.'),
('intelligent','지적인','adj.','Dolphins are intelligent animals.','돌고래는 지능적인 동물이다.'),
('intense','강렬한','adj.','The training was intense.','훈련이 강도 높았다.'),
('internal','내부의','adj.','It is an internal company matter.','그것은 회사 내부 문제다.'),
('international','국제적인','adj.','She works at an international firm.','그녀는 국제 기업에서 일한다.'),
('jealous','질투하는','adj.','Do not be jealous of others.','다른 사람을 질투하지 마라.'),
('joyful','기쁜','adj.','It was a joyful reunion.','그것은 기쁜 재회였다.'),
('junior','후배의','adj.','He is my junior at work.','그는 직장 후배다.'),
('keen','열심인','adj.','She is keen on photography.','그녀는 사진에 열심이다.'),
('kind','친절한','adj.','He is kind to everyone.','그는 모두에게 친절하다.'),
('large','큰','adj.','Order a large pizza.','라지 피자를 주문하세요.'),
('late','늦은','adj.','Sorry, I am late.','늦어서 미안해요.'),
('lazy','게으른','adj.','The lazy cat sleeps all day.','게으른 고양이는 하루 종일 잔다.'),
('legal','합법적인','adj.','The contract is legal.','그 계약은 합법적이다.'),
('light','가벼운','adj.','The bag is light to carry.','그 가방은 들고 다니기 가볍다.'),
('likely','~할 것 같은','adj.','It is likely to rain.','비가 올 것 같다.'),
('local','지역의','adj.','Try the local food.','현지 음식을 먹어 보세요.'),
('lonely','외로운','adj.','He felt lonely abroad.','그는 해외에서 외로움을 느꼈다.'),
('loose','느슨한','adj.','The screw is loose.','나사가 느슨하다.'),
('loud','시끄러운','adj.','The music is too loud.','음악이 너무 시끄럽다.'),
('lovely','사랑스러운','adj.','What a lovely day!','정말 멋진 날이야!'),
('loyal','충성스러운','adj.','He is loyal to his team.','그는 자신의 팀에 충실하다.'),
('lucky','운 좋은','adj.','You are lucky to have friends.','친구가 있다니 운이 좋다.'),
('main','주요한','adj.','The main entrance is closed.','정문이 닫혀 있다.'),
('major','주요한','adj.','Tourism is a major industry.','관광은 주요 산업이다.'),
('male','남성의','adj.','The male bird sings loudly.','수컷 새가 크게 노래한다.'),
('mature','성숙한','adj.','She is mature for her age.','그녀는 나이에 비해 성숙하다.'),
('medical','의학의','adj.','He needs medical care.','그는 치료가 필요하다.'),
('mental','정신의','adj.','Mental health matters.','정신 건강은 중요하다.'),
('messy','지저분한','adj.','My desk is messy.','내 책상은 지저분하다.'),
('mild','온화한','adj.','The winter was mild this year.','올해 겨울은 온화했다.'),
('minor','사소한','adj.','It was a minor mistake.','그것은 사소한 실수였다.'),
('modern','현대의','adj.','The building has a modern design.','그 건물은 현대적인 디자인이다.'),
('moral','도덕적인','adj.','It is a moral question.','그것은 도덕적 문제다.'),
('narrow','좁은','adj.','The street is too narrow.','그 길은 너무 좁다.'),
('native','토박이의','adj.','She is a native speaker.','그녀는 원어민이다.'),
('natural','자연의','adj.','Honey is a natural sweetener.','꿀은 천연 감미료다.'),
('necessary','필요한','adj.','Bring the necessary documents.','필요한 서류를 가져오세요.'),
('negative','부정적인','adj.','Avoid negative thinking.','부정적인 생각을 피하라.'),
('nervous','긴장한','adj.','I was nervous before the speech.','연설 전에 긴장했다.'),
('normal','정상의','adj.','Everything is back to normal.','모든 것이 정상으로 돌아왔다.'),
('obvious','명백한','adj.','The answer is obvious.','답은 명백하다.'),
('odd','이상한','adj.','That is an odd question.','그것 참 이상한 질문이다.'),
('official','공식의','adj.','The official results are out.','공식 결과가 나왔다.'),
('ordinary','평범한','adj.','It was an ordinary day.','평범한 하루였다.'),
('original','원래의','adj.','Keep the original receipt.','원본 영수증을 보관하세요.'),
('outdoor','야외의','adj.','We enjoy outdoor sports.','우리는 야외 스포츠를 즐긴다.'),
('painful','고통스러운','adj.','The injury was painful.','그 부상은 고통스러웠다.'),
('pale','창백한','adj.','You look pale today.','너 오늘 창백해 보여.'),
('particular','특정한','adj.','Pay attention to this particular point.','이 특정 부분에 주의하세요.'),
('peaceful','평화로운','adj.','The village is peaceful.','그 마을은 평화롭다.'),
('perfect','완벽한','adj.','Practice makes perfect.','연습이 완벽을 만든다.'),
('permanent','영구적인','adj.','He got a permanent job.','그는 정규직을 얻었다.'),
('personal','개인의','adj.','It is a personal choice.','그것은 개인의 선택이다.'),
('physical','신체의','adj.','Physical activity boosts energy.','신체 활동은 에너지를 높인다.'),
('plain','소박한','adj.','She wore a plain dress.','그녀는 소박한 드레스를 입었다.'),
('pleasant','즐거운','adj.','We had a pleasant chat.','우리는 즐거운 대화를 나눴다.'),
('polite','예의 바른','adj.','The staff were polite.','직원들이 예의 발랐다.'),
('poor','가난한','adj.','They helped poor families.','그들은 가난한 가정을 도왔다.'),
('popular','인기 있는','adj.','The song is popular now.','그 노래는 지금 인기다.'),
('positive','긍정적인','adj.','Keep a positive mind.','긍정적인 마음을 유지하라.'),
('powerful','강력한','adj.','Words are powerful.','말에는 힘이 있다.'),
('practical','실용적인','adj.','The gift was practical.','그 선물은 실용적이었다.'),
('precious','귀중한','adj.','Time is precious.','시간은 귀중하다.'),
('previous','이전의','adj.','Check the previous page.','이전 페이지를 확인하세요.'),
('primary','주요한','adj.','Safety is the primary concern.','안전이 최우선 관심사다.'),
('private','사적인','adj.','This is a private matter.','이것은 사적인 문제다.'),
('professional','전문적인','adj.','She gave professional advice.','그녀는 전문적인 조언을 했다.'),
('proper','적절한','adj.','Use the proper tools.','적절한 도구를 사용하세요.'),
('proud','자랑스러운','adj.','I am proud of you.','나는 네가 자랑스럽다.'),
('public','공공의','adj.','Use public transportation.','대중교통을 이용하세요.'),
('pure','순수한','adj.','The water is pure and clean.','그 물은 순수하고 깨끗하다.'),
('quick','빠른','adj.','Take a quick break.','짧은 휴식을 취하세요.'),
('quiet','조용한','adj.','The library is quiet.','도서관은 조용하다.'),
('rapid','급속한','adj.','The city saw rapid growth.','그 도시는 급속한 성장을 겪었다.'),
('rare','드문','adj.','This stamp is very rare.','이 우표는 매우 희귀하다.'),
('raw','날것의','adj.','Do not eat raw eggs.','날달걀을 먹지 마세요.'),
('ready','준비된','adj.','Dinner is ready.','저녁이 준비됐다.'),
('real','진짜의','adj.','Is this diamond real?','이 다이아몬드 진짜야?'),
('reasonable','합리적인','adj.','The price is reasonable.','가격이 합리적이다.'),
('recent','최근의','adj.','Read the recent news.','최근 뉴스를 읽어 보세요.'),
('regular','규칙적인','adj.','Regular exercise is key.','규칙적인 운동이 핵심이다.'),
('remote','외딴','adj.','They live in a remote village.','그들은 외딴 마을에 산다.'),
('responsible','책임감 있는','adj.','He is a responsible worker.','그는 책임감 있는 직원이다.'),
('rich','부유한','adj.','The soil here is rich.','이곳 토양은 비옥하다.'),
('rough','거친','adj.','The road is rough.','그 길은 울퉁불퉁하다.'),
('round','둥근','adj.','The table is round.','그 테이블은 둥글다.'),
('royal','왕실의','adj.','We toured the royal palace.','우리는 왕궁을 관람했다.'),
('rude','무례한','adj.','Do not be rude to staff.','직원에게 무례하게 굴지 마세요.'),
('sad','슬픈','adj.','The movie ending was sad.','영화 결말이 슬펐다.'),
('safe','안전한','adj.','Keep your passwords safe.','비밀번호를 안전하게 보관하세요.'),
('scared','겁먹은','adj.','The kitten looked scared.','새끼 고양이가 겁먹은 듯 보였다.'),
('secure','안전한','adj.','The building is secure.','그 건물은 안전하다.'),
('senior','상급의','adj.','She is a senior manager.','그녀는 수석 매니저다.'),
('sensitive','민감한','adj.','My skin is sensitive.','내 피부는 민감하다.'),
('serious','심각한','adj.','It is not a serious problem.','심각한 문제는 아니다.'),
('several','몇몇의','adj.','I called several times.','여러 번 전화했다.'),
('sharp','날카로운','adj.','The knife is very sharp.','그 칼은 매우 날카롭다.'),
('shiny','빛나는','adj.','He polished the shiny shoes.','그는 반짝이는 구두를 닦았다.'),
('short','짧은','adj.','Write a short note.','짧은 메모를 쓰세요.'),
('shy','수줍은','adj.','The shy boy hid behind his mom.','수줍은 소년이 엄마 뒤에 숨었다.'),
('silent','조용한','adj.','The hall went silent.','홀이 조용해졌다.'),
('silly','어리석은','adj.','It was a silly joke.','그것은 우스꽝스러운 농담이었다.'),
('similar','비슷한','adj.','Our tastes are similar.','우리 취향은 비슷하다.'),
('simple','단순한','adj.','Keep the design simple.','디자인을 단순하게 유지하세요.'),
('sincere','진실한','adj.','Please accept my sincere thanks.','저의 진심 어린 감사를 받아 주세요.'),
('skillful','능숙한','adj.','She is skillful with tools.','그녀는 도구를 능숙하게 다룬다.'),
('slight','약간의','adj.','There is a slight delay.','약간의 지연이 있다.'),
('slow','느린','adj.','The internet is slow today.','오늘 인터넷이 느리다.'),
('smart','똑똑한','adj.','That was a smart move.','그것은 똑똑한 행동이었다.'),
('smooth','매끄러운','adj.','The surface is smooth.','표면이 매끄럽다.'),
('social','사회적인','adj.','Humans are social beings.','인간은 사회적 존재다.'),
('soft','부드러운','adj.','The pillow is soft.','베개가 부드럽다.'),
('solid','단단한','adj.','The bridge has a solid base.','그 다리는 단단한 기초를 가졌다.'),
('special','특별한','adj.','Today is a special day.','오늘은 특별한 날이다.'),
('specific','구체적인','adj.','Give me specific examples.','구체적인 예를 들어 주세요.'),
('steady','꾸준한','adj.','Make steady progress.','꾸준한 발전을 이뤄라.'),
('strange','이상한','adj.','I heard a strange sound.','이상한 소리를 들었다.'),
('strict','엄격한','adj.','The teacher is strict but fair.','그 선생님은 엄격하지만 공정하다.'),
('strong','강한','adj.','Strong habits build success.','강한 습관이 성공을 만든다.'),
('stupid','어리석은','adj.','There are no stupid questions.','어리석은 질문이란 없다.'),
('sudden','갑작스러운','adj.','There was a sudden change.','갑작스러운 변화가 있었다.'),
('sufficient','충분한','adj.','We have sufficient supplies.','우리는 충분한 물자가 있다.'),
('suitable','적합한','adj.','The movie is suitable for kids.','그 영화는 아이들에게 적합하다.'),
('sweet','달콤한','adj.','The grapes are sweet.','포도가 달다.'),
('tall','키 큰','adj.','The tower is very tall.','그 탑은 매우 높다.'),
('terrible','끔찍한','adj.','The traffic was terrible.','교통이 끔찍했다.'),
('thick','두꺼운','adj.','Wear a thick coat.','두꺼운 코트를 입으세요.'),
('thin','얇은','adj.','The ice is too thin.','얼음이 너무 얇다.'),
('thirsty','목마른','adj.','I am thirsty after running.','달리고 나니 목이 마르다.'),
('tight','꽉 끼는','adj.','These shoes are tight.','이 신발은 꽉 낀다.'),
('tiny','아주 작은','adj.','A tiny bird sat on the wire.','아주 작은 새가 전선에 앉았다.'),
('tired','피곤한','adj.','I am tired after work.','일 끝나고 피곤하다.'),
('total','전체의','adj.','The total cost is fifty dollars.','총 비용은 50달러다.'),
('tough','힘든','adj.','It was a tough decision.','힘든 결정이었다.'),
('typical','전형적인','adj.','It is a typical Monday.','전형적인 월요일이다.'),
('unique','독특한','adj.','Everyone has unique talents.','모두가 고유한 재능을 가졌다.'),
('urgent','긴급한','adj.','I got an urgent call.','긴급한 전화를 받았다.'),
('useful','유용한','adj.','The app is very useful.','그 앱은 매우 유용하다.'),
('usual','평소의','adj.','I took my usual route.','평소 다니던 길로 갔다.'),
('valuable','가치 있는','adj.','Experience is valuable.','경험은 가치 있다.'),
('vast','광대한','adj.','The desert is vast.','그 사막은 광활하다.'),
('visible','보이는','adj.','The moon is visible tonight.','오늘 밤 달이 보인다.'),
('vivid','생생한','adj.','I had a vivid dream.','생생한 꿈을 꿨다.'),
('warm','따뜻한','adj.','The soup is still warm.','수프가 아직 따뜻하다.'),
('weak','약한','adj.','The signal is weak here.','여기는 신호가 약하다.'),
('wet','젖은','adj.','My shoes are wet from rain.','비에 신발이 젖었다.'),
('whole','전체의','adj.','I spent the whole day reading.','하루 종일 책을 읽었다.'),
('wide','넓은','adj.','The river is wide here.','이곳은 강폭이 넓다.'),
('wild','야생의','adj.','Wild flowers cover the hill.','야생화가 언덕을 덮고 있다.'),
('wise','지혜로운','adj.','A wise person listens first.','지혜로운 사람은 먼저 듣는다.'),
('wonderful','멋진','adj.','We had a wonderful time.','우리는 멋진 시간을 보냈다.'),
('worried','걱정하는','adj.','She was worried about the exam.','그녀는 시험을 걱정했다.'),
('worthy','가치 있는','adj.','It is a worthy cause.','그것은 가치 있는 대의다.'),
('young','어린','adj.','The young artist is talented.','그 젊은 예술가는 재능 있다.'),
('actually','실제로','adv.','Actually, I agree with you.','사실 나는 너에게 동의해.'),
('almost','거의','adv.','We are almost there.','우리는 거의 다 왔다.'),
('already','이미','adv.','The bus already left.','버스가 이미 떠났다.'),
('carefully','조심스럽게','adv.','Read the contract carefully.','계약서를 신중하게 읽으세요.'),
('certainly','확실히','adv.','I will certainly help you.','확실히 너를 도울게.'),
('clearly','분명히','adv.','Speak clearly, please.','분명하게 말해 주세요.'),
('completely','완전히','adv.','I completely forgot the meeting.','회의를 완전히 잊어버렸다.'),
('constantly','끊임없이','adv.','Technology constantly changes.','기술은 끊임없이 변한다.'),
('definitely','분명히','adv.','I will definitely come.','꼭 갈게.'),
('especially','특히','adv.','I love fruit, especially mangoes.','나는 과일, 특히 망고를 좋아한다.'),
('eventually','결국','adv.','Eventually, she succeeded.','결국 그녀는 성공했다.'),
('exactly','정확히','adv.','That is exactly what I meant.','그게 정확히 내 말이야.'),
('finally','마침내','adv.','We finally arrived home.','우리는 마침내 집에 도착했다.'),
('frequently','자주','adv.','He frequently visits the gym.','그는 자주 체육관에 간다.'),
('gradually','점차','adv.','The weather gradually improved.','날씨가 점차 좋아졌다.'),
('immediately','즉시','adv.','Call me immediately.','즉시 전화해.'),
('luckily','다행히','adv.','Luckily, no one was hurt.','다행히 아무도 다치지 않았다.'),
('mostly','대부분','adv.','The audience was mostly students.','관객은 대부분 학생이었다.'),
('naturally','자연스럽게','adv.','Talent comes naturally to her.','그녀에게 재능은 자연스럽게 따라온다.'),
('nearly','거의','adv.','It is nearly midnight.','거의 자정이다.'),
('obviously','분명히','adv.','Obviously, he was tired.','분명히 그는 피곤했다.'),
('occasionally','가끔','adv.','I occasionally eat out.','나는 가끔 외식한다.'),
('probably','아마','adv.','It will probably rain tomorrow.','내일 아마 비가 올 것이다.'),
('quickly','빠르게','adv.','She quickly solved the problem.','그녀는 문제를 빠르게 풀었다.'),
('quietly','조용히','adv.','He quietly left the room.','그는 조용히 방을 나갔다.'),
('rarely','드물게','adv.','He rarely complains.','그는 좀처럼 불평하지 않는다.'),
('recently','최근에','adv.','I recently started jogging.','최근에 조깅을 시작했다.'),
('regularly','정기적으로','adv.','Back up your files regularly.','파일을 정기적으로 백업하세요.'),
('seriously','진지하게','adv.','Take your health seriously.','건강을 진지하게 생각하세요.'),
('slowly','천천히','adv.','Drive slowly in the snow.','눈길에서는 천천히 운전하세요.'),
('suddenly','갑자기','adv.','Suddenly, the lights went out.','갑자기 불이 꺼졌다.'),
('totally','완전히','adv.','I totally understand.','완전히 이해해.'),
('usually','보통','adv.','I usually wake at seven.','나는 보통 7시에 일어난다.')
on conflict (en) do nothing;
