-- FocusCoin 단어 시드 Part 1/5 — 동사 (200개)
insert into focuscoin_words (en, kr, pos, ex, ex_kr) values
('abandon','버리다','v.','He abandoned the old plan.','그는 오래된 계획을 버렸다.'),
('absorb','흡수하다','v.','Plants absorb water.','식물은 물을 흡수한다.'),
('accept','받아들이다','v.','She accepted the offer.','그녀는 제안을 받아들였다.'),
('accuse','비난하다','v.','Do not accuse others easily.','다른 사람을 쉽게 비난하지 마라.'),
('adapt','적응하다','v.','We must adapt to change.','우리는 변화에 적응해야 한다.'),
('add','더하다','v.','Add some salt to the soup.','수프에 소금을 조금 더하세요.'),
('adjust','조정하다','v.','Adjust the volume, please.','볼륨을 조정해 주세요.'),
('admire','존경하다','v.','I admire her courage.','나는 그녀의 용기를 존경한다.'),
('admit','인정하다','v.','He admitted his mistake.','그는 자신의 실수를 인정했다.'),
('adopt','채택하다','v.','The team adopted a new method.','팀은 새로운 방법을 채택했다.'),
('advise','조언하다','v.','I advise you to rest.','나는 너에게 쉬라고 조언한다.'),
('afford','여유가 되다','v.','I cannot afford a new car.','나는 새 차를 살 여유가 없다.'),
('agree','동의하다','v.','I agree with your opinion.','나는 너의 의견에 동의한다.'),
('aim','목표로 하다','v.','Aim high and work hard.','목표를 높게 잡고 열심히 일하라.'),
('allow','허락하다','v.','They allow pets here.','이곳은 반려동물이 허용된다.'),
('analyze','분석하다','v.','Analyze the data carefully.','데이터를 신중하게 분석하라.'),
('announce','발표하다','v.','They announced the winner.','그들은 우승자를 발표했다.'),
('annoy','짜증나게 하다','v.','The noise annoys me.','그 소음이 나를 짜증나게 한다.'),
('anticipate','예상하다','v.','We anticipate good results.','우리는 좋은 결과를 예상한다.'),
('apologize','사과하다','v.','He apologized for being late.','그는 늦은 것에 대해 사과했다.'),
('appear','나타나다','v.','A rainbow appeared in the sky.','하늘에 무지개가 나타났다.'),
('apply','지원하다','v.','She applied for the job.','그녀는 그 일자리에 지원했다.'),
('appreciate','감사하다','v.','I appreciate your help.','당신의 도움에 감사합니다.'),
('approach','다가가다','v.','Winter is approaching.','겨울이 다가오고 있다.'),
('approve','승인하다','v.','The manager approved the plan.','매니저가 그 계획을 승인했다.'),
('argue','논쟁하다','v.','They argued about money.','그들은 돈 문제로 논쟁했다.'),
('arrange','정리하다','v.','Arrange the books by size.','책을 크기별로 정리하세요.'),
('arrive','도착하다','v.','The train arrived on time.','기차가 정시에 도착했다.'),
('assist','돕다','v.','I will assist you with the work.','내가 그 일을 도와줄게.'),
('assume','가정하다','v.','Do not assume the worst.','최악을 가정하지 마라.'),
('attach','붙이다','v.','Attach the file to the email.','이메일에 파일을 첨부하세요.'),
('attempt','시도하다','v.','He attempted a new recipe.','그는 새로운 요리법을 시도했다.'),
('attend','참석하다','v.','She attended the meeting.','그녀는 회의에 참석했다.'),
('attract','끌어들이다','v.','Flowers attract bees.','꽃은 벌을 끌어들인다.'),
('avoid','피하다','v.','Avoid sugary drinks.','단 음료를 피하세요.'),
('bake','굽다','v.','She baked some cookies.','그녀는 쿠키를 구웠다.'),
('behave','행동하다','v.','Please behave politely.','예의 바르게 행동해 주세요.'),
('believe','믿다','v.','I believe in you.','나는 너를 믿는다.'),
('belong','속하다','v.','This book belongs to me.','이 책은 내 것이다.'),
('blame','탓하다','v.','Do not blame yourself.','자신을 탓하지 마라.'),
('boil','끓이다','v.','Boil the water first.','먼저 물을 끓이세요.'),
('borrow','빌리다','v.','Can I borrow your pen?','펜 좀 빌릴 수 있을까?'),
('breathe','숨쉬다','v.','Breathe deeply and relax.','깊게 숨쉬고 긴장을 푸세요.'),
('build','짓다','v.','They built a new house.','그들은 새 집을 지었다.'),
('calculate','계산하다','v.','Calculate the total cost.','총 비용을 계산하세요.'),
('cancel','취소하다','v.','The flight was canceled.','비행기가 취소되었다.'),
('carry','나르다','v.','He carried the heavy box.','그는 무거운 상자를 날랐다.'),
('celebrate','축하하다','v.','We celebrated her birthday.','우리는 그녀의 생일을 축하했다.'),
('challenge','도전하다','v.','Challenge yourself every day.','매일 자신에게 도전하라.'),
('change','바꾸다','v.','She changed her hairstyle.','그녀는 머리 스타일을 바꿨다.'),
('charge','청구하다','v.','They charged me ten dollars.','그들은 나에게 10달러를 청구했다.'),
('chase','쫓다','v.','The dog chased the ball.','개가 공을 쫓아갔다.'),
('cheer','응원하다','v.','We cheered for our team.','우리는 우리 팀을 응원했다.'),
('choose','선택하다','v.','Choose what you love.','네가 사랑하는 것을 선택하라.'),
('claim','주장하다','v.','He claimed he was right.','그는 자신이 옳다고 주장했다.'),
('climb','오르다','v.','We climbed the mountain.','우리는 산을 올랐다.'),
('collect','모으다','v.','She collects old coins.','그녀는 오래된 동전을 모은다.'),
('combine','결합하다','v.','Combine flour and sugar.','밀가루와 설탕을 섞으세요.'),
('communicate','소통하다','v.','We communicate by email.','우리는 이메일로 소통한다.'),
('compare','비교하다','v.','Compare the two prices.','두 가격을 비교해 보세요.'),
('compete','경쟁하다','v.','They competed for first place.','그들은 1등을 위해 경쟁했다.'),
('complain','불평하다','v.','He complained about the food.','그는 음식에 대해 불평했다.'),
('complete','완료하다','v.','Complete the form first.','먼저 양식을 작성하세요.'),
('concentrate','집중하다','v.','Concentrate on your goal.','목표에 집중하라.'),
('confirm','확인하다','v.','Please confirm your booking.','예약을 확인해 주세요.'),
('connect','연결하다','v.','Connect the cable here.','케이블을 여기에 연결하세요.'),
('consider','고려하다','v.','Consider all the options.','모든 선택지를 고려하라.'),
('contain','포함하다','v.','This drink contains caffeine.','이 음료에는 카페인이 들어 있다.'),
('continue','계속하다','v.','Continue your good work.','좋은 일을 계속하세요.'),
('contribute','기여하다','v.','Everyone contributed ideas.','모두가 아이디어를 보탰다.'),
('convince','설득하다','v.','She convinced me to join.','그녀는 내가 참여하도록 설득했다.'),
('cook','요리하다','v.','He cooks dinner every day.','그는 매일 저녁을 요리한다.'),
('count','세다','v.','Count from one to ten.','1부터 10까지 세어 보세요.'),
('cover','덮다','v.','Cover the pot with a lid.','냄비를 뚜껑으로 덮으세요.'),
('create','창조하다','v.','Artists create new works.','예술가들은 새로운 작품을 창조한다.'),
('cross','건너다','v.','Cross the street carefully.','길을 조심해서 건너세요.'),
('cry','울다','v.','The baby cried all night.','아기가 밤새 울었다.'),
('damage','손상시키다','v.','The storm damaged the roof.','폭풍이 지붕을 손상시켰다.'),
('dance','춤추다','v.','They danced at the party.','그들은 파티에서 춤을 췄다.'),
('decide','결정하다','v.','She decided to study abroad.','그녀는 유학을 가기로 결정했다.'),
('declare','선언하다','v.','He declared his goals.','그는 자신의 목표를 선언했다.'),
('decorate','장식하다','v.','We decorated the room.','우리는 방을 장식했다.'),
('decrease','감소하다','v.','Sales decreased last month.','지난달 매출이 감소했다.'),
('defend','방어하다','v.','He defended his opinion.','그는 자신의 의견을 방어했다.'),
('delay','미루다','v.','Do not delay your homework.','숙제를 미루지 마라.'),
('deliver','배달하다','v.','They deliver food fast.','그들은 음식을 빨리 배달한다.'),
('demand','요구하다','v.','Customers demand quality.','고객들은 품질을 요구한다.'),
('deny','부인하다','v.','He denied the rumor.','그는 그 소문을 부인했다.'),
('depend','의존하다','v.','It depends on the weather.','그것은 날씨에 달려 있다.'),
('describe','묘사하다','v.','Describe your ideal day.','당신의 이상적인 하루를 묘사해 보세요.'),
('deserve','받을 자격이 있다','v.','You deserve a break.','너는 휴식을 받을 자격이 있다.'),
('design','설계하다','v.','She designed the poster.','그녀는 포스터를 디자인했다.'),
('destroy','파괴하다','v.','The fire destroyed the building.','화재가 건물을 파괴했다.'),
('develop','발전시키다','v.','Develop good habits early.','좋은 습관을 일찍 길러라.'),
('disappear','사라지다','v.','The sun disappeared behind clouds.','해가 구름 뒤로 사라졌다.'),
('discover','발견하다','v.','They discovered a new island.','그들은 새로운 섬을 발견했다.'),
('discuss','토론하다','v.','We discussed the project.','우리는 프로젝트에 대해 토론했다.'),
('divide','나누다','v.','Divide the cake into six.','케이크를 여섯 조각으로 나누세요.'),
('donate','기부하다','v.','She donated old clothes.','그녀는 헌 옷을 기부했다.'),
('doubt','의심하다','v.','I doubt that story.','나는 그 이야기를 의심한다.'),
('draw','그리다','v.','He draws cartoons well.','그는 만화를 잘 그린다.'),
('dream','꿈꾸다','v.','She dreams of traveling.','그녀는 여행을 꿈꾼다.'),
('drop','떨어뜨리다','v.','I dropped my phone.','나는 휴대폰을 떨어뜨렸다.'),
('earn','벌다','v.','He earns money on weekends.','그는 주말에 돈을 번다.'),
('educate','교육하다','v.','Schools educate children.','학교는 아이들을 교육한다.'),
('elect','선출하다','v.','They elected a new leader.','그들은 새 지도자를 선출했다.'),
('embarrass','당황하게 하다','v.','The question embarrassed him.','그 질문이 그를 당황하게 했다.'),
('emphasize','강조하다','v.','She emphasized the deadline.','그녀는 마감일을 강조했다.'),
('employ','고용하다','v.','The company employs 100 people.','그 회사는 100명을 고용한다.'),
('encourage','격려하다','v.','Teachers encourage students.','선생님들은 학생들을 격려한다.'),
('enjoy','즐기다','v.','Enjoy your meal.','식사 맛있게 하세요.'),
('enter','들어가다','v.','Enter through the front door.','정문으로 들어가세요.'),
('escape','탈출하다','v.','The bird escaped from the cage.','새가 새장에서 탈출했다.'),
('establish','설립하다','v.','They established a new school.','그들은 새 학교를 설립했다.'),
('estimate','추정하다','v.','Estimate the total time.','전체 시간을 추정해 보세요.'),
('examine','조사하다','v.','The doctor examined the patient.','의사가 환자를 진찰했다.'),
('exchange','교환하다','v.','We exchanged phone numbers.','우리는 전화번호를 교환했다.'),
('exist','존재하다','v.','Life exists in the ocean.','바다에는 생명이 존재한다.'),
('expand','확장하다','v.','The company expanded overseas.','그 회사는 해외로 확장했다.'),
('expect','기대하다','v.','I expect good news.','나는 좋은 소식을 기대한다.'),
('experience','경험하다','v.','She experienced many cultures.','그녀는 많은 문화를 경험했다.'),
('explain','설명하다','v.','Explain the rules simply.','규칙을 간단히 설명하세요.'),
('explore','탐험하다','v.','They explored the forest.','그들은 숲을 탐험했다.'),
('express','표현하다','v.','Express your feelings honestly.','감정을 솔직하게 표현하라.'),
('extend','연장하다','v.','They extended the deadline.','그들은 마감일을 연장했다.'),
('fail','실패하다','v.','Do not fear to fail.','실패를 두려워하지 마라.'),
('feed','먹이를 주다','v.','Feed the cat twice a day.','고양이에게 하루 두 번 먹이를 주세요.'),
('fix','고치다','v.','He fixed the broken chair.','그는 부러진 의자를 고쳤다.'),
('float','뜨다','v.','Wood floats on water.','나무는 물에 뜬다.'),
('fold','접다','v.','Fold the paper in half.','종이를 반으로 접으세요.'),
('follow','따르다','v.','Follow the instructions.','지시 사항을 따르세요.'),
('forgive','용서하다','v.','Forgive and move on.','용서하고 앞으로 나아가라.'),
('freeze','얼다','v.','The lake froze last night.','어젯밤 호수가 얼었다.'),
('frighten','겁주다','v.','The thunder frightened the dog.','천둥이 개를 겁먹게 했다.'),
('gain','얻다','v.','You gain skill with practice.','연습으로 기술을 얻는다.'),
('gather','모이다','v.','We gathered in the park.','우리는 공원에 모였다.'),
('generate','만들어내다','v.','Solar panels generate power.','태양광 패널은 전력을 만들어낸다.'),
('grab','움켜잡다','v.','He grabbed his bag and ran.','그는 가방을 움켜잡고 달렸다.'),
('greet','인사하다','v.','She greeted us warmly.','그녀는 우리를 따뜻하게 맞이했다.'),
('grow','자라다','v.','Tomatoes grow fast in summer.','토마토는 여름에 빨리 자란다.'),
('guess','추측하다','v.','Guess my age.','내 나이를 맞혀 봐.'),
('guide','안내하다','v.','He guided us through the city.','그는 도시를 안내해 주었다.'),
('handle','다루다','v.','Handle the glass with care.','유리를 조심해서 다루세요.'),
('hang','걸다','v.','Hang your coat here.','코트를 여기에 거세요.'),
('happen','일어나다','v.','Accidents happen sometimes.','사고는 가끔 일어난다.'),
('harvest','수확하다','v.','Farmers harvest rice in fall.','농부들은 가을에 쌀을 수확한다.'),
('hate','싫어하다','v.','I hate waking up early.','나는 일찍 일어나는 것을 싫어한다.'),
('heal','치유하다','v.','Time heals all wounds.','시간이 모든 상처를 치유한다.'),
('hesitate','망설이다','v.','Do not hesitate to ask.','망설이지 말고 물어보세요.'),
('hide','숨다','v.','The cat hid under the bed.','고양이가 침대 밑에 숨었다.'),
('hire','고용하다','v.','They hired a new chef.','그들은 새 요리사를 고용했다.'),
('hold','잡다','v.','Hold my hand tightly.','내 손을 꽉 잡아.'),
('hope','희망하다','v.','I hope you feel better.','네가 나아지길 바란다.'),
('hug','안다','v.','She hugged her mother.','그녀는 어머니를 안았다.'),
('identify','식별하다','v.','Identify the main problem.','주요 문제를 파악하세요.'),
('ignore','무시하다','v.','Ignore the rude comments.','무례한 댓글은 무시하세요.'),
('imagine','상상하다','v.','Imagine a better future.','더 나은 미래를 상상해 보라.'),
('imitate','모방하다','v.','Children imitate adults.','아이들은 어른을 모방한다.'),
('include','포함하다','v.','The price includes tax.','가격에는 세금이 포함된다.'),
('increase','증가하다','v.','Demand increased rapidly.','수요가 빠르게 증가했다.'),
('indicate','나타내다','v.','The sign indicates danger.','그 표지판은 위험을 나타낸다.'),
('influence','영향을 주다','v.','Music influences our mood.','음악은 우리 기분에 영향을 준다.'),
('inform','알리다','v.','Please inform me of changes.','변경 사항을 알려 주세요.'),
('insist','고집하다','v.','He insisted on paying.','그는 자기가 내겠다고 고집했다.'),
('inspire','영감을 주다','v.','Her story inspires many people.','그녀의 이야기는 많은 사람에게 영감을 준다.'),
('install','설치하다','v.','Install the app first.','먼저 앱을 설치하세요.'),
('intend','의도하다','v.','I intend to finish today.','나는 오늘 끝낼 작정이다.'),
('interrupt','방해하다','v.','Do not interrupt the speaker.','발표자를 방해하지 마세요.'),
('introduce','소개하다','v.','Let me introduce myself.','제 소개를 하겠습니다.'),
('invent','발명하다','v.','Edison invented the light bulb.','에디슨은 전구를 발명했다.'),
('invest','투자하다','v.','Invest in your education.','자신의 교육에 투자하라.'),
('invite','초대하다','v.','They invited us to dinner.','그들은 우리를 저녁 식사에 초대했다.'),
('involve','관련시키다','v.','The job involves travel.','그 일은 출장을 포함한다.'),
('join','가입하다','v.','Join our book club.','우리 독서 모임에 가입하세요.'),
('judge','판단하다','v.','Do not judge by appearance.','겉모습으로 판단하지 마라.'),
('jump','뛰다','v.','The kids jumped with joy.','아이들이 기뻐서 뛰었다.'),
('keep','유지하다','v.','Keep your room clean.','방을 깨끗하게 유지하세요.'),
('knock','두드리다','v.','Knock before entering.','들어가기 전에 노크하세요.'),
('last','지속되다','v.','The meeting lasted two hours.','회의는 두 시간 동안 계속됐다.'),
('laugh','웃다','v.','We laughed at the joke.','우리는 그 농담에 웃었다.'),
('lead','이끌다','v.','She leads the design team.','그녀는 디자인팀을 이끈다.'),
('lend','빌려주다','v.','Can you lend me a book?','책 한 권 빌려줄 수 있어?'),
('lift','들어올리다','v.','Lift the box carefully.','상자를 조심해서 들어 올리세요.'),
('locate','위치를 찾다','v.','Locate the nearest exit.','가장 가까운 출구를 찾으세요.'),
('maintain','유지하다','v.','Maintain a healthy diet.','건강한 식단을 유지하라.'),
('manage','관리하다','v.','She manages her time well.','그녀는 시간을 잘 관리한다.'),
('measure','측정하다','v.','Measure the length twice.','길이를 두 번 측정하세요.'),
('melt','녹다','v.','The snow melted quickly.','눈이 빠르게 녹았다.'),
('mention','언급하다','v.','He mentioned your name.','그가 네 이름을 언급했다.'),
('mix','섞다','v.','Mix the eggs and milk.','달걀과 우유를 섞으세요.'),
('move','움직이다','v.','We moved to a new city.','우리는 새 도시로 이사했다.'),
('notice','알아차리다','v.','I noticed a small change.','나는 작은 변화를 알아차렸다.'),
('obey','순종하다','v.','Drivers must obey traffic rules.','운전자는 교통 규칙을 지켜야 한다.'),
('observe','관찰하다','v.','Observe the stars at night.','밤에 별을 관찰해 보세요.'),
('obtain','얻다','v.','He obtained a license.','그는 면허를 취득했다.'),
('occur','발생하다','v.','The error occurred twice.','그 오류는 두 번 발생했다.'),
('offer','제안하다','v.','They offered me a job.','그들은 나에게 일자리를 제안했다.'),
('operate','작동하다','v.','The machine operates all day.','그 기계는 하루 종일 작동한다.'),
('order','주문하다','v.','We ordered pizza for lunch.','우리는 점심으로 피자를 주문했다.'),
('organize','조직하다','v.','Organize your desk first.','먼저 책상을 정리하세요.'),
('owe','빚지다','v.','I owe you a favor.','나는 너에게 신세를 졌다.'),
('own','소유하다','v.','They own two cars.','그들은 차 두 대를 소유하고 있다.')
on conflict (en) do nothing;
