-- FocusCoin 단어 시드 Part 4/5 — 명사 마무리 + 형용사 (200개)
insert into focuscoin_words (en, kr, pos, ex, ex_kr) values
('question','질문','n.','Ask me any question.','어떤 질문이든 하세요.'),
('reason','이유','n.','Give me a good reason.','타당한 이유를 말해 주세요.'),
('recipe','요리법','n.','This recipe is easy to follow.','이 요리법은 따라 하기 쉽다.'),
('region','지역','n.','This region is famous for apples.','이 지역은 사과로 유명하다.'),
('relationship','관계','n.','They have a close relationship.','그들은 가까운 관계다.'),
('religion','종교','n.','Respect every religion.','모든 종교를 존중하라.'),
('republic','공화국','n.','Korea is a republic.','한국은 공화국이다.'),
('reputation','평판','n.','The hotel has a good reputation.','그 호텔은 평판이 좋다.'),
('request','요청','n.','We received your request.','귀하의 요청을 받았습니다.'),
('resource','자원','n.','Water is a precious resource.','물은 귀중한 자원이다.'),
('responsibility','책임','n.','Take responsibility for your actions.','자신의 행동에 책임을 져라.'),
('result','결과','n.','The test results came out.','시험 결과가 나왔다.'),
('revolution','혁명','n.','The industrial revolution changed everything.','산업 혁명은 모든 것을 바꿨다.'),
('risk','위험','n.','Taking risks can pay off.','위험을 감수하면 보상이 따를 수 있다.'),
('role','역할','n.','Parents play an important role.','부모는 중요한 역할을 한다.'),
('routine','일과','n.','A morning routine helps focus.','아침 루틴은 집중에 도움이 된다.'),
('safety','안전','n.','Safety comes first.','안전이 최우선이다.'),
('salary','급여','n.','The salary is paid monthly.','급여는 매달 지급된다.'),
('sample','샘플','n.','Try a free sample.','무료 샘플을 사용해 보세요.'),
('satisfaction','만족','n.','Customer satisfaction is our goal.','고객 만족이 우리의 목표다.'),
('scale','규모','n.','The project is large in scale.','그 프로젝트는 규모가 크다.'),
('scene','장면','n.','The last scene made me cry.','마지막 장면에 울었다.'),
('schedule','일정','n.','Check your schedule first.','먼저 일정을 확인하세요.'),
('science','과학','n.','Science explains the world.','과학은 세상을 설명한다.'),
('season','계절','n.','Autumn is my favorite season.','가을은 내가 가장 좋아하는 계절이다.'),
('secret','비밀','n.','Can you keep a secret?','비밀 지킬 수 있어?'),
('section','구역','n.','The book section is upstairs.','도서 구역은 위층이다.'),
('security','보안','n.','Update your security settings.','보안 설정을 업데이트하세요.'),
('sentence','문장','n.','Write a complete sentence.','완전한 문장을 쓰세요.'),
('service','서비스','n.','The service was excellent.','서비스가 훌륭했다.'),
('shadow','그림자','n.','The tree cast a long shadow.','나무가 긴 그림자를 드리웠다.'),
('shape','모양','n.','Cut the paper into a star shape.','종이를 별 모양으로 자르세요.'),
('signal','신호','n.','Wait for the signal.','신호를 기다리세요.'),
('silence','침묵','n.','Silence filled the room.','침묵이 방을 가득 채웠다.'),
('situation','상황','n.','Stay calm in any situation.','어떤 상황에서도 침착하라.'),
('skill','기술','n.','Coding is a useful skill.','코딩은 유용한 기술이다.'),
('society','사회','n.','Education benefits society.','교육은 사회에 이익이 된다.'),
('solution','해결책','n.','We found a simple solution.','우리는 간단한 해결책을 찾았다.'),
('source','출처','n.','Check the source of the news.','뉴스의 출처를 확인하세요.'),
('speech','연설','n.','Her speech moved the audience.','그녀의 연설은 청중을 감동시켰다.'),
('speed','속도','n.','Reduce your speed in rain.','빗길에서는 속도를 줄이세요.'),
('spirit','정신','n.','Team spirit matters in sports.','스포츠에서는 팀 정신이 중요하다.'),
('standard','기준','n.','The quality meets the standard.','품질이 기준을 충족한다.'),
('statement','진술','n.','He made a public statement.','그는 공개 성명을 발표했다.'),
('station','역','n.','The station is five minutes away.','역은 5분 거리에 있다.'),
('statue','동상','n.','The statue stands in the square.','동상이 광장에 서 있다.'),
('step','단계','n.','Follow the steps in order.','순서대로 단계를 따르세요.'),
('stomach','위','n.','My stomach hurts a little.','배가 조금 아프다.'),
('strategy','전략','n.','We need a new strategy.','우리는 새로운 전략이 필요하다.'),
('strength','힘','n.','Know your strengths.','자신의 강점을 알아라.'),
('stress','스트레스','n.','Exercise reduces stress.','운동은 스트레스를 줄인다.'),
('structure','구조','n.','The structure is very stable.','그 구조는 매우 안정적이다.'),
('subject','과목','n.','English is my favorite subject.','영어는 내가 가장 좋아하는 과목이다.'),
('substance','물질','n.','The substance is harmless.','그 물질은 무해하다.'),
('success','성공','n.','Success takes time.','성공에는 시간이 걸린다.'),
('suggestion','제안','n.','Thanks for your suggestion.','제안 감사합니다.'),
('summary','요약','n.','Write a short summary.','짧은 요약을 쓰세요.'),
('surface','표면','n.','Clean the surface first.','먼저 표면을 닦으세요.'),
('symbol','상징','n.','The dove is a symbol of peace.','비둘기는 평화의 상징이다.'),
('system','시스템','n.','The system works well.','그 시스템은 잘 작동한다.'),
('talent','재능','n.','She has a talent for music.','그녀는 음악에 재능이 있다.'),
('task','과제','n.','Finish one task at a time.','한 번에 한 가지 일을 끝내라.'),
('taste','맛','n.','The soup has a rich taste.','그 수프는 맛이 진하다.'),
('technology','기술','n.','Technology changes our lives.','기술은 우리 삶을 바꾼다.'),
('temperature','온도','n.','The temperature dropped suddenly.','기온이 갑자기 떨어졌다.'),
('theory','이론','n.','The theory was proven true.','그 이론은 사실로 증명되었다.'),
('thought','생각','n.','Share your thoughts with us.','당신의 생각을 들려주세요.'),
('threat','위협','n.','Pollution is a threat to health.','오염은 건강에 위협이 된다.'),
('tradition','전통','n.','The festival is an old tradition.','그 축제는 오랜 전통이다.'),
('traffic','교통','n.','The traffic is heavy today.','오늘 교통이 혼잡하다.'),
('treasure','보물','n.','They found a hidden treasure.','그들은 숨겨진 보물을 발견했다.'),
('treatment','치료','n.','The treatment was successful.','치료가 성공적이었다.'),
('trend','유행','n.','Short videos are the trend.','짧은 영상이 유행이다.'),
('trouble','문제','n.','He is in big trouble.','그는 큰 곤경에 처해 있다.'),
('truth','진실','n.','Always tell the truth.','항상 진실을 말하라.'),
('value','가치','n.','Know the value of time.','시간의 가치를 알아라.'),
('variety','다양성','n.','The menu offers a variety of dishes.','그 메뉴는 다양한 요리를 제공한다.'),
('vehicle','차량','n.','Electric vehicles are popular now.','전기차가 요즘 인기다.'),
('victory','승리','n.','The team celebrated the victory.','팀은 승리를 축하했다.'),
('view','전망','n.','The room has an ocean view.','그 방은 바다 전망이다.'),
('village','마을','n.','The village is quiet and peaceful.','그 마을은 조용하고 평화롭다.'),
('voice','목소리','n.','She has a beautiful voice.','그녀는 아름다운 목소리를 가졌다.'),
('volume','음량','n.','Turn down the volume.','음량을 줄이세요.'),
('war','전쟁','n.','The war ended in 1953.','그 전쟁은 1953년에 끝났다.'),
('warmth','따뜻함','n.','I felt the warmth of the sun.','태양의 따뜻함을 느꼈다.'),
('weakness','약점','n.','Turn weakness into strength.','약점을 강점으로 바꿔라.'),
('wealth','부','n.','Health is better than wealth.','건강이 부보다 낫다.'),
('weapon','무기','n.','Knowledge is a powerful weapon.','지식은 강력한 무기다.'),
('weather','날씨','n.','The weather is perfect today.','오늘 날씨가 완벽하다.'),
('weekend','주말','n.','Have a nice weekend.','즐거운 주말 보내세요.'),
('weight','무게','n.','Check the weight of the bag.','가방의 무게를 확인하세요.'),
('wisdom','지혜','n.','Age brings wisdom.','나이가 들면 지혜가 생긴다.'),
('wish','소원','n.','Make a wish on your birthday.','생일에 소원을 빌어 보세요.'),
('worth','가치','n.','The painting is worth millions.','그 그림은 수백만 달러의 가치가 있다.'),
('youth','젊음','n.','Enjoy your youth fully.','젊음을 마음껏 즐겨라.'),
('absent','결석한','adj.','He was absent from school.','그는 학교에 결석했다.'),
('accurate','정확한','adj.','The clock is very accurate.','그 시계는 매우 정확하다.'),
('active','활동적인','adj.','She stays active every day.','그녀는 매일 활동적으로 지낸다.'),
('actual','실제의','adj.','The actual price was lower.','실제 가격은 더 낮았다.'),
('afraid','두려워하는','adj.','Do not be afraid of change.','변화를 두려워하지 마라.'),
('aggressive','공격적인','adj.','The dog looked aggressive.','그 개는 공격적으로 보였다.'),
('alive','살아있는','adj.','The tradition is still alive.','그 전통은 여전히 살아 있다.'),
('amazing','놀라운','adj.','The view was amazing.','그 경치는 놀라웠다.'),
('ancient','고대의','adj.','We visited ancient ruins.','우리는 고대 유적을 방문했다.'),
('angry','화난','adj.','He was angry about the delay.','그는 지연에 화가 났다.'),
('anxious','불안한','adj.','She felt anxious before the test.','그녀는 시험 전에 불안했다.'),
('attractive','매력적인','adj.','The offer sounds attractive.','그 제안은 매력적으로 들린다.'),
('available','이용 가능한','adj.','The room is available now.','그 방은 지금 이용 가능하다.'),
('aware','알고 있는','adj.','Be aware of the risks.','위험을 인지하라.'),
('awkward','어색한','adj.','There was an awkward silence.','어색한 침묵이 흘렀다.'),
('basic','기본적인','adj.','Learn the basic rules first.','기본 규칙부터 배우세요.'),
('bitter','쓴','adj.','The coffee tastes bitter.','그 커피는 쓴맛이 난다.'),
('brave','용감한','adj.','The brave firefighter saved them.','용감한 소방관이 그들을 구했다.'),
('brief','간단한','adj.','Give a brief summary.','간단한 요약을 해 주세요.'),
('bright','밝은','adj.','The room is bright and airy.','그 방은 밝고 쾌적하다.'),
('brilliant','뛰어난','adj.','What a brilliant idea!','정말 뛰어난 아이디어야!'),
('broad','넓은','adj.','He has broad shoulders.','그는 어깨가 넓다.'),
('busy','바쁜','adj.','I am busy this afternoon.','오늘 오후에는 바쁘다.'),
('calm','차분한','adj.','Stay calm and think.','침착하게 생각하라.'),
('capable','유능한','adj.','She is capable of great things.','그녀는 큰일을 할 능력이 있다.'),
('careful','조심스러운','adj.','Be careful on the ice.','빙판에서 조심하세요.'),
('careless','부주의한','adj.','A careless mistake cost him.','부주의한 실수가 그에게 손해를 입혔다.'),
('certain','확실한','adj.','I am certain about the answer.','나는 그 답이 확실하다.'),
('cheap','싼','adj.','The tickets were surprisingly cheap.','표가 놀랍게도 쌌다.'),
('cheerful','쾌활한','adj.','Her cheerful smile brightens the room.','그녀의 밝은 미소가 방을 환하게 한다.'),
('chief','주된','adj.','Safety is our chief concern.','안전이 우리의 주된 관심사다.'),
('clear','명확한','adj.','The instructions were clear.','지시 사항이 명확했다.'),
('clever','영리한','adj.','The clever fox escaped.','영리한 여우가 도망쳤다.'),
('close','가까운','adj.','The store is close to my house.','그 가게는 우리 집과 가깝다.'),
('comfortable','편안한','adj.','This chair is very comfortable.','이 의자는 매우 편안하다.'),
('common','흔한','adj.','Kim is a common Korean surname.','김은 흔한 한국 성씨다.'),
('complex','복잡한','adj.','The problem is more complex.','그 문제는 더 복잡하다.'),
('convenient','편리한','adj.','Online shopping is convenient.','온라인 쇼핑은 편리하다.'),
('correct','올바른','adj.','Choose the correct answer.','올바른 답을 고르세요.'),
('crowded','붐비는','adj.','The subway was crowded.','지하철이 붐볐다.'),
('curious','호기심 많은','adj.','Children are naturally curious.','아이들은 천성적으로 호기심이 많다.'),
('current','현재의','adj.','The current situation is stable.','현재 상황은 안정적이다.'),
('dangerous','위험한','adj.','Driving fast is dangerous.','과속 운전은 위험하다.'),
('dark','어두운','adj.','The room was completely dark.','방이 완전히 어두웠다.'),
('deep','깊은','adj.','The lake is very deep.','그 호수는 매우 깊다.'),
('delicious','맛있는','adj.','The cake was delicious.','케이크가 맛있었다.'),
('different','다른','adj.','We have different tastes.','우리는 취향이 다르다.'),
('difficult','어려운','adj.','The exam was difficult.','시험이 어려웠다.'),
('direct','직접적인','adj.','Take the direct route.','직행 경로로 가세요.'),
('dirty','더러운','adj.','Wash the dirty dishes.','더러운 접시를 닦으세요.'),
('distant','먼','adj.','We heard distant thunder.','멀리서 천둥소리가 들렸다.'),
('diverse','다양한','adj.','The city has a diverse culture.','그 도시는 다양한 문화를 가졌다.'),
('domestic','국내의','adj.','Domestic travel is increasing.','국내 여행이 늘고 있다.'),
('dry','마른','adj.','The towel is dry now.','수건이 이제 말랐다.'),
('eager','열망하는','adj.','She is eager to learn.','그녀는 배우기를 열망한다.'),
('early','이른','adj.','I woke up early today.','오늘 일찍 일어났다.'),
('easy','쉬운','adj.','The quiz was easy.','퀴즈가 쉬웠다.'),
('economic','경제의','adj.','Economic growth slowed down.','경제 성장이 둔화되었다.'),
('effective','효과적인','adj.','The method is very effective.','그 방법은 매우 효과적이다.'),
('efficient','효율적인','adj.','The new system is efficient.','새 시스템은 효율적이다.'),
('elderly','나이 든','adj.','Help elderly people cross.','노인들이 건너는 것을 도와드리세요.'),
('electric','전기의','adj.','Electric cars are quiet.','전기차는 조용하다.'),
('empty','빈','adj.','The bottle is empty.','병이 비어 있다.'),
('enormous','거대한','adj.','An enormous wave hit the shore.','거대한 파도가 해안을 덮쳤다.'),
('entire','전체의','adj.','I read the entire book.','나는 책 전체를 읽었다.'),
('equal','평등한','adj.','All people are equal.','모든 사람은 평등하다.'),
('essential','필수적인','adj.','Sleep is essential for health.','수면은 건강에 필수적이다.'),
('exact','정확한','adj.','Tell me the exact time.','정확한 시간을 알려 주세요.'),
('excellent','훌륭한','adj.','Her work is excellent.','그녀의 작품은 훌륭하다.'),
('exciting','신나는','adj.','The game was exciting.','그 경기는 흥미진진했다.'),
('expensive','비싼','adj.','The watch is too expensive.','그 시계는 너무 비싸다.'),
('external','외부의','adj.','Ignore external pressure.','외부 압력을 무시하라.'),
('extreme','극단적인','adj.','Avoid extreme diets.','극단적인 다이어트를 피하세요.'),
('fair','공정한','adj.','The judge made a fair decision.','판사는 공정한 결정을 내렸다.'),
('faithful','충실한','adj.','The dog was faithful to its owner.','그 개는 주인에게 충실했다.'),
('famous','유명한','adj.','The city is famous for food.','그 도시는 음식으로 유명하다.'),
('fancy','화려한','adj.','They ate at a fancy restaurant.','그들은 고급 식당에서 식사했다.'),
('fantastic','환상적인','adj.','We had a fantastic trip.','우리는 환상적인 여행을 했다.'),
('fast','빠른','adj.','The train is very fast.','그 기차는 매우 빠르다.'),
('favorite','가장 좋아하는','adj.','Blue is my favorite color.','파란색은 내가 가장 좋아하는 색이다.'),
('female','여성의','adj.','The female lion hunts.','암사자가 사냥한다.'),
('fierce','사나운','adj.','The competition was fierce.','경쟁이 치열했다.'),
('final','마지막의','adj.','This is the final round.','이번이 마지막 라운드다.'),
('financial','재정의','adj.','Set financial goals early.','재정 목표를 일찍 세워라.'),
('fit','건강한','adj.','He stays fit by running.','그는 달리기로 건강을 유지한다.'),
('flat','평평한','adj.','The land here is flat.','이곳 땅은 평평하다.'),
('flexible','유연한','adj.','My schedule is flexible.','내 일정은 유연하다.'),
('foreign','외국의','adj.','She speaks two foreign languages.','그녀는 두 개의 외국어를 한다.'),
('formal','격식 있는','adj.','Wear formal clothes to the event.','행사에는 정장을 입으세요.'),
('fortunate','운이 좋은','adj.','We were fortunate with the weather.','우리는 날씨 운이 좋았다.'),
('fragile','깨지기 쉬운','adj.','Handle the fragile box gently.','깨지기 쉬운 상자를 조심히 다루세요.'),
('frequent','빈번한','adj.','He is a frequent visitor.','그는 자주 오는 방문객이다.'),
('fresh','신선한','adj.','Buy fresh vegetables.','신선한 채소를 사세요.'),
('friendly','친절한','adj.','The staff were friendly.','직원들이 친절했다.'),
('frozen','얼어붙은','adj.','The frozen lake looks beautiful.','얼어붙은 호수가 아름다워 보인다.'),
('funny','웃긴','adj.','He told a funny story.','그는 웃긴 이야기를 했다.'),
('general','일반적인','adj.','In general, I agree.','일반적으로 나는 동의한다.'),
('gentle','부드러운','adj.','A gentle breeze blew.','부드러운 바람이 불었다.'),
('genuine','진짜의','adj.','Her smile was genuine.','그녀의 미소는 진심이었다.'),
('giant','거대한','adj.','A giant tree stands in the park.','거대한 나무가 공원에 서 있다.'),
('global','세계적인','adj.','Climate change is a global issue.','기후 변화는 세계적인 문제다.'),
('glorious','영광스러운','adj.','It was a glorious morning.','눈부신 아침이었다.'),
('golden','황금의','adj.','Do not miss the golden chance.','황금 같은 기회를 놓치지 마라.'),
('grand','웅장한','adj.','The hotel lobby is grand.','호텔 로비가 웅장하다.'),
('grateful','감사하는','adj.','I am grateful for your support.','당신의 지원에 감사한다.'),
('great','위대한','adj.','She is a great teacher.','그녀는 훌륭한 선생님이다.'),
('guilty','유죄의','adj.','He felt guilty about lying.','그는 거짓말한 것에 죄책감을 느꼈다.')
on conflict (en) do nothing;
