-- FocusCoin 단어 시드 Part 2/5 — 동사 이어서 + 명사 (200개)
insert into focuscoin_words (en, kr, pos, ex, ex_kr) values
('pack','짐을 싸다','v.','Pack your bags tonight.','오늘 밤 짐을 싸세요.'),
('paint','칠하다','v.','We painted the wall white.','우리는 벽을 하얗게 칠했다.'),
('participate','참여하다','v.','Everyone participated in the game.','모두가 게임에 참여했다.'),
('perform','수행하다','v.','The band performed live.','그 밴드는 라이브로 공연했다.'),
('persuade','설득하다','v.','She persuaded him to stay.','그녀는 그가 머물도록 설득했다.'),
('plant','심다','v.','We planted trees in spring.','우리는 봄에 나무를 심었다.'),
('point','가리키다','v.','He pointed at the map.','그는 지도를 가리켰다.'),
('postpone','연기하다','v.','They postponed the picnic.','그들은 소풍을 연기했다.'),
('pour','붓다','v.','Pour the tea slowly.','차를 천천히 따르세요.'),
('practice','연습하다','v.','Practice makes perfect.','연습이 완벽을 만든다.'),
('praise','칭찬하다','v.','The coach praised the players.','코치는 선수들을 칭찬했다.'),
('predict','예측하다','v.','No one can predict the future.','아무도 미래를 예측할 수 없다.'),
('prefer','선호하다','v.','I prefer tea to coffee.','나는 커피보다 차를 선호한다.'),
('prepare','준비하다','v.','Prepare for the interview.','면접을 준비하세요.'),
('pretend','~인 척하다','v.','He pretended to be asleep.','그는 자는 척했다.'),
('prevent','예방하다','v.','Exercise prevents many diseases.','운동은 많은 질병을 예방한다.'),
('produce','생산하다','v.','The factory produces toys.','그 공장은 장난감을 생산한다.'),
('promise','약속하다','v.','I promise to be on time.','정시에 오겠다고 약속할게.'),
('promote','홍보하다','v.','They promoted the new product.','그들은 신제품을 홍보했다.'),
('pronounce','발음하다','v.','How do you pronounce this word?','이 단어는 어떻게 발음하나요?'),
('protect','보호하다','v.','Helmets protect your head.','헬멧은 머리를 보호한다.'),
('prove','증명하다','v.','The results prove the theory.','결과가 그 이론을 증명한다.'),
('provide','제공하다','v.','The hotel provides breakfast.','그 호텔은 아침 식사를 제공한다.'),
('publish','출판하다','v.','She published her first novel.','그녀는 첫 소설을 출판했다.'),
('pull','당기다','v.','Pull the door to open.','문을 당겨서 여세요.'),
('punish','처벌하다','v.','The school punished the cheater.','학교는 부정행위자를 처벌했다.'),
('purchase','구매하다','v.','He purchased a new laptop.','그는 새 노트북을 구매했다.'),
('push','밀다','v.','Push the button to start.','시작하려면 버튼을 누르세요.'),
('quit','그만두다','v.','He quit smoking last year.','그는 작년에 담배를 끊었다.'),
('raise','올리다','v.','Raise your hand to speak.','발언하려면 손을 드세요.'),
('reach','도달하다','v.','We reached the top at noon.','우리는 정오에 정상에 도달했다.'),
('react','반응하다','v.','How did she react to the news?','그녀는 그 소식에 어떻게 반응했나요?'),
('realize','깨닫다','v.','I realized my mistake too late.','나는 너무 늦게 실수를 깨달았다.'),
('receive','받다','v.','She received a gift.','그녀는 선물을 받았다.'),
('recommend','추천하다','v.','I recommend this restaurant.','이 식당을 추천합니다.'),
('recover','회복하다','v.','He recovered from the flu.','그는 독감에서 회복했다.'),
('reduce','줄이다','v.','Reduce screen time at night.','밤에는 화면 보는 시간을 줄이세요.'),
('refer','참조하다','v.','Refer to the manual.','설명서를 참조하세요.'),
('reflect','반영하다','v.','The lake reflects the sky.','호수가 하늘을 비춘다.'),
('refuse','거절하다','v.','She refused the invitation.','그녀는 초대를 거절했다.'),
('regret','후회하다','v.','You will not regret this choice.','이 선택을 후회하지 않을 것이다.'),
('relax','휴식하다','v.','Relax after a long day.','긴 하루 후에는 휴식을 취하세요.'),
('release','발표하다','v.','They released a new album.','그들은 새 앨범을 발표했다.'),
('rely','의지하다','v.','You can rely on me.','너는 나를 믿어도 돼.'),
('remain','남다','v.','Only two tickets remain.','표가 두 장만 남았다.'),
('remember','기억하다','v.','Remember to lock the door.','문 잠그는 것을 기억하세요.'),
('remind','상기시키다','v.','Remind me at five.','5시에 알려 줘.'),
('remove','제거하다','v.','Remove your shoes here.','여기서 신발을 벗으세요.'),
('rent','임대하다','v.','We rented a small apartment.','우리는 작은 아파트를 임대했다.'),
('repair','수리하다','v.','He repaired the old clock.','그는 오래된 시계를 수리했다.'),
('repeat','반복하다','v.','Repeat after me.','나를 따라 말하세요.'),
('replace','교체하다','v.','Replace the old battery.','오래된 배터리를 교체하세요.'),
('reply','답장하다','v.','Please reply by Friday.','금요일까지 답장해 주세요.'),
('represent','대표하다','v.','She represents our school.','그녀는 우리 학교를 대표한다.'),
('require','요구하다','v.','The job requires patience.','그 일은 인내심을 요구한다.'),
('rescue','구조하다','v.','Firefighters rescued the cat.','소방관들이 고양이를 구조했다.'),
('research','연구하다','v.','They research climate change.','그들은 기후 변화를 연구한다.'),
('reserve','예약하다','v.','I reserved a table for two.','두 명 자리를 예약했다.'),
('resolve','해결하다','v.','They resolved the conflict.','그들은 갈등을 해결했다.'),
('respect','존중하다','v.','Respect different opinions.','다른 의견을 존중하라.'),
('respond','응답하다','v.','He responded quickly.','그는 빠르게 응답했다.'),
('rest','쉬다','v.','Rest your eyes for a while.','잠시 눈을 쉬게 하세요.'),
('return','돌아오다','v.','She returned home safely.','그녀는 무사히 집에 돌아왔다.'),
('review','검토하다','v.','Review your notes before the test.','시험 전에 노트를 복습하세요.'),
('rise','오르다','v.','The sun rises in the east.','해는 동쪽에서 뜬다.'),
('roll','구르다','v.','The ball rolled down the hill.','공이 언덕 아래로 굴러갔다.'),
('rub','문지르다','v.','Rub your hands to warm them.','손을 비벼서 따뜻하게 하세요.'),
('sail','항해하다','v.','They sailed across the sea.','그들은 바다를 항해했다.'),
('satisfy','만족시키다','v.','The result satisfied everyone.','그 결과는 모두를 만족시켰다.'),
('save','저축하다','v.','Save money for the future.','미래를 위해 돈을 모아라.'),
('scream','비명을 지르다','v.','She screamed at the spider.','그녀는 거미를 보고 비명을 질렀다.'),
('search','검색하다','v.','Search for the answer online.','온라인에서 답을 검색해 보세요.'),
('seek','찾다','v.','Seek advice from experts.','전문가에게 조언을 구하라.'),
('seem','~처럼 보이다','v.','You seem tired today.','너 오늘 피곤해 보여.'),
('select','선택하다','v.','Select your favorite color.','좋아하는 색을 선택하세요.'),
('separate','분리하다','v.','Separate the trash properly.','쓰레기를 제대로 분리하세요.'),
('serve','제공하다','v.','They serve lunch at noon.','그들은 정오에 점심을 제공한다.'),
('settle','정착하다','v.','They settled in a small town.','그들은 작은 마을에 정착했다.'),
('shake','흔들다','v.','Shake the bottle well.','병을 잘 흔드세요.'),
('share','공유하다','v.','Share your ideas with us.','당신의 아이디어를 공유해 주세요.'),
('shine','빛나다','v.','The stars shine brightly.','별들이 밝게 빛난다.'),
('shout','외치다','v.','He shouted for help.','그는 도와달라고 외쳤다.'),
('sign','서명하다','v.','Sign at the bottom of the page.','페이지 하단에 서명하세요.'),
('sink','가라앉다','v.','The boat sank slowly.','배가 천천히 가라앉았다.'),
('slip','미끄러지다','v.','Be careful not to slip.','미끄러지지 않게 조심하세요.'),
('solve','풀다','v.','Solve the puzzle together.','퍼즐을 함께 풀어 보세요.'),
('spend','쓰다','v.','He spends weekends reading.','그는 주말을 독서하며 보낸다.'),
('spill','쏟다','v.','I spilled coffee on my shirt.','셔츠에 커피를 쏟았다.'),
('spread','퍼지다','v.','The news spread quickly.','그 소식은 빠르게 퍼졌다.'),
('squeeze','짜다','v.','Squeeze the lemon juice.','레몬즙을 짜세요.'),
('steal','훔치다','v.','Someone stole my bike.','누군가 내 자전거를 훔쳤다.'),
('stretch','늘이다','v.','Stretch before you exercise.','운동 전에 스트레칭하세요.'),
('struggle','분투하다','v.','He struggled with math.','그는 수학과 씨름했다.'),
('submit','제출하다','v.','Submit the report by Monday.','월요일까지 보고서를 제출하세요.'),
('succeed','성공하다','v.','Work hard and you will succeed.','열심히 하면 성공할 것이다.'),
('suffer','고통받다','v.','He suffered from a headache.','그는 두통에 시달렸다.'),
('suggest','제안하다','v.','I suggest a short break.','짧은 휴식을 제안합니다.'),
('supply','공급하다','v.','The farm supplies fresh eggs.','그 농장은 신선한 달걀을 공급한다.'),
('support','지지하다','v.','My family supports my dream.','가족은 내 꿈을 지지한다.'),
('suppose','가정하다','v.','Suppose you won the lottery.','복권에 당첨됐다고 가정해 보자.'),
('surround','둘러싸다','v.','Mountains surround the village.','산이 마을을 둘러싸고 있다.'),
('survive','생존하다','v.','Camels survive in the desert.','낙타는 사막에서 생존한다.'),
('swim','수영하다','v.','She swims every morning.','그녀는 매일 아침 수영한다.'),
('throw','던지다','v.','Throw the ball to me.','공을 나에게 던져.'),
('translate','번역하다','v.','Translate this sentence.','이 문장을 번역하세요.'),
('travel','여행하다','v.','We traveled around Europe.','우리는 유럽을 여행했다.'),
('treat','대하다','v.','Treat others kindly.','다른 사람을 친절하게 대하라.'),
('trust','신뢰하다','v.','Trust your instincts.','너의 직감을 믿어라.'),
('understand','이해하다','v.','Now I understand the lesson.','이제 그 수업을 이해한다.'),
('unite','연합하다','v.','The teams united for the cause.','팀들은 대의를 위해 뭉쳤다.'),
('upload','업로드하다','v.','Upload the photo here.','사진을 여기에 업로드하세요.'),
('vote','투표하다','v.','Citizens vote every four years.','시민들은 4년마다 투표한다.'),
('wait','기다리다','v.','Wait for the green light.','초록불을 기다리세요.'),
('warn','경고하다','v.','They warned us about the storm.','그들은 폭풍에 대해 경고했다.'),
('waste','낭비하다','v.','Do not waste your time.','시간을 낭비하지 마라.'),
('wave','손을 흔들다','v.','She waved goodbye.','그녀는 손을 흔들어 작별 인사를 했다.'),
('whisper','속삭이다','v.','He whispered the secret.','그는 비밀을 속삭였다.'),
('wonder','궁금해하다','v.','I wonder what happened.','무슨 일이 있었는지 궁금하다.'),
('wrap','포장하다','v.','Wrap the gift nicely.','선물을 예쁘게 포장하세요.'),
('ability','능력','n.','She has the ability to lead.','그녀는 이끄는 능력이 있다.'),
('absence','부재','n.','His absence was noticed.','그의 부재가 눈에 띄었다.'),
('accident','사고','n.','The accident blocked the road.','사고로 도로가 막혔다.'),
('achievement','업적','n.','Graduation is a big achievement.','졸업은 큰 성취다.'),
('activity','활동','n.','Outdoor activities are fun.','야외 활동은 재미있다.'),
('advantage','이점','n.','Speed is our advantage.','속도가 우리의 강점이다.'),
('adventure','모험','n.','Life is a great adventure.','인생은 위대한 모험이다.'),
('advice','조언','n.','Thanks for your advice.','조언 고마워요.'),
('amount','양','n.','Drink a small amount of water.','소량의 물을 마시세요.'),
('animal','동물','n.','Wild animals live in the forest.','야생 동물은 숲에 산다.'),
('answer','대답','n.','Your answer is correct.','당신의 대답이 맞습니다.'),
('apartment','아파트','n.','They live in a small apartment.','그들은 작은 아파트에 산다.'),
('appearance','외모','n.','Do not judge by appearance.','외모로 판단하지 마라.'),
('appointment','약속','n.','I have a doctor appointment.','병원 예약이 있다.'),
('area','지역','n.','This area is quiet at night.','이 지역은 밤에 조용하다.'),
('argument','논쟁','n.','They had a small argument.','그들은 작은 말다툼을 했다.'),
('article','기사','n.','I read an interesting article.','흥미로운 기사를 읽었다.'),
('atmosphere','분위기','n.','The cafe has a cozy atmosphere.','그 카페는 아늑한 분위기다.'),
('attention','주의','n.','Pay attention to the details.','세부 사항에 주의를 기울이세요.'),
('attitude','태도','n.','A positive attitude helps.','긍정적인 태도가 도움이 된다.'),
('audience','관객','n.','The audience clapped loudly.','관객들이 크게 박수를 쳤다.'),
('average','평균','n.','The average score was 80.','평균 점수는 80점이었다.'),
('balance','균형','n.','Keep a balance between work and rest.','일과 휴식의 균형을 유지하라.'),
('basket','바구니','n.','Put the fruit in the basket.','과일을 바구니에 담으세요.'),
('beauty','아름다움','n.','The beauty of nature amazes me.','자연의 아름다움이 나를 놀라게 한다.'),
('behavior','행동','n.','Good behavior is rewarded.','좋은 행동은 보상받는다.'),
('benefit','혜택','n.','Exercise has many benefits.','운동은 많은 이점이 있다.'),
('bill','청구서','n.','The electricity bill arrived.','전기 요금 청구서가 도착했다.'),
('birth','탄생','n.','They celebrated the birth of their son.','그들은 아들의 탄생을 축하했다.'),
('blanket','담요','n.','Cover yourself with a blanket.','담요를 덮으세요.'),
('blood','피','n.','Donating blood saves lives.','헌혈은 생명을 구한다.'),
('border','국경','n.','The river forms the border.','그 강이 국경을 이룬다.'),
('bottle','병','n.','Recycle plastic bottles.','플라스틱 병을 재활용하세요.'),
('bottom','바닥','n.','Check the bottom of the box.','상자 바닥을 확인하세요.'),
('branch','가지','n.','A bird sat on the branch.','새가 가지에 앉았다.'),
('bridge','다리','n.','The bridge crosses the river.','그 다리는 강을 가로지른다.'),
('budget','예산','n.','Plan your monthly budget.','월 예산을 계획하세요.'),
('career','경력','n.','She built a great career.','그녀는 훌륭한 경력을 쌓았다.'),
('ceiling','천장','n.','The ceiling is painted white.','천장은 흰색으로 칠해져 있다.'),
('century','세기','n.','The castle is five centuries old.','그 성은 5세기 됐다.'),
('ceremony','의식','n.','The wedding ceremony was beautiful.','결혼식이 아름다웠다.'),
('chance','기회','n.','Give me one more chance.','한 번 더 기회를 주세요.'),
('character','성격','n.','She has a strong character.','그녀는 강한 성격을 가졌다.'),
('charity','자선','n.','He gives to charity monthly.','그는 매달 자선 단체에 기부한다.'),
('chemistry','화학','n.','Chemistry is my favorite subject.','화학은 내가 가장 좋아하는 과목이다.'),
('childhood','어린 시절','n.','I had a happy childhood.','나는 행복한 어린 시절을 보냈다.'),
('choice','선택','n.','It was a wise choice.','그것은 현명한 선택이었다.'),
('citizen','시민','n.','Every citizen has rights.','모든 시민은 권리가 있다.'),
('climate','기후','n.','The climate here is mild.','이곳의 기후는 온화하다.'),
('clothes','옷','n.','Pack warm clothes for winter.','겨울을 위해 따뜻한 옷을 챙기세요.'),
('coast','해안','n.','We drove along the coast.','우리는 해안을 따라 운전했다.'),
('comfort','편안함','n.','The sofa offers great comfort.','그 소파는 아주 편안하다.'),
('community','공동체','n.','Our community is friendly.','우리 동네는 친절하다.'),
('company','회사','n.','She works for a tech company.','그녀는 기술 회사에서 일한다.'),
('competition','경쟁','n.','The competition was fierce.','경쟁이 치열했다.'),
('concert','콘서트','n.','The concert starts at seven.','콘서트는 7시에 시작한다.'),
('condition','상태','n.','The car is in good condition.','그 차는 상태가 좋다.'),
('confidence','자신감','n.','Practice builds confidence.','연습은 자신감을 길러 준다.'),
('connection','연결','n.','The internet connection is slow.','인터넷 연결이 느리다.'),
('conversation','대화','n.','We had a long conversation.','우리는 긴 대화를 나눴다.'),
('cost','비용','n.','The cost of living is rising.','생활비가 오르고 있다.'),
('cotton','면','n.','This shirt is made of cotton.','이 셔츠는 면으로 만들어졌다.'),
('courage','용기','n.','It takes courage to start.','시작하려면 용기가 필요하다.'),
('culture','문화','n.','Korean culture is popular worldwide.','한국 문화는 전 세계적으로 인기 있다.'),
('curiosity','호기심','n.','Curiosity drives learning.','호기심이 배움을 이끈다.'),
('custom','관습','n.','Bowing is a Korean custom.','절은 한국의 관습이다.'),
('customer','고객','n.','The customer is always right.','고객은 항상 옳다.'),
('damage','손상','n.','The storm caused damage.','폭풍이 피해를 일으켰다.'),
('danger','위험','n.','The sign warns of danger.','그 표지판은 위험을 경고한다.'),
('deadline','마감일','n.','The deadline is tomorrow.','마감일은 내일이다.'),
('decision','결정','n.','It was a hard decision.','그것은 어려운 결정이었다.'),
('degree','학위','n.','She earned a master degree.','그녀는 석사 학위를 받았다.'),
('delivery','배달','n.','Free delivery on all orders.','모든 주문 무료 배송.'),
('design','디자인','n.','I love the simple design.','나는 단순한 디자인이 좋다.'),
('detail','세부 사항','n.','Check every detail twice.','모든 세부 사항을 두 번 확인하세요.'),
('device','기기','n.','Turn off all devices.','모든 기기를 끄세요.'),
('diet','식단','n.','A balanced diet is important.','균형 잡힌 식단이 중요하다.')
on conflict (en) do nothing;
